on:
  workflow_dispatch:
  
jobs:
  openssl:
    name: Recover With OpenSSL
    runs-on: ubuntu-20.04
    steps:
     - name: Generate key
       env:
          APP_KEY: ${{ secrets.APP_PRIVATE_KEY }}
       run: |
         echo -n "$APP_KEY" > ~/p.key
      
     - name: Generate hash
       run: |
         echo -n "followme" | openssl dgst -sha512 -sign ~/p.key | openssl base64
